name: Build and Release for 1.16

on:
  push:
    branches: [ 1.16-release ]

jobs:
  release:
    name: Builds and Release on Curseforge, Modrinth, Github and Saps
    runs-on: ubuntu-latest
    steps:
      - name: Build with Gradle and publish on github
        run: echo "build"
#        uses: nanite/workflows/.github/workflows/standard-release.yml@v1
#        with:
#          java-version: 8
#          curse-publish-task: ""
#        secrets:
#          saps-token: ${{ secrets.SAPS_TOKEN }}

      - name: Release on Modrinth & Curseforge
        run: echo "release"
#        uses: Kir-Antipov/mc-publish@v3.2
#        with:
#          modrinth-id: MNBGnhBw
#          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
#  
#          curseforge-id: 845405
#          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
#  
#          loaders: forge
#          game-versions: |
#            1.16.3
#            1.16.4
#            1.16.5
#          java: 8