name: Build and Release for 1.16

on:
  push:
    branches: [ 1.16-release ]

jobs:
  build:
    name: Builds and Release on Github and Saps
    uses: nanite/workflows/.github/workflows/standard-release.yml@v1
    with:
      java-version: 1.8
      curse-publish-task: ""
    secrets:
      saps-token: ${{ secrets.SAPS_TOKEN }}
  
  publish:
    steps:
      - name: Publish Minecraft Mods
        uses: Kir-Antipov/mc-publish@v3.2
        needs: build
        with:
          modrinth-id: MNBGnhBw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
  
          curseforge-id: 845405
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
  
          loaders: forge
          game-versions: |
            1.16.3
            1.16.4
            1.16.5
          java: 8